server:
  port: 9001
  servlet:
    context-path: /camunda-workflow

spring:
  application:
    name: workflow

  datasource.url: jdbc:postgresql://localhost:5432/workflow
  datasource:
    username: db_user
    password: db_password
  jpa:
    properties:
      hibernate:
        format_sql: true
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      generate-ddl: true
      properties:
        hibernate:
          format_sql: true
          ddl-auto: create-update

management:
  endpoints:
    web:
      base-path: "/actuator"
      exposure:
        include: "health, info, metrics, prometheus"
      path-mapping:
        health: "health"
        info: "info"
        metrics: "metrics"
    jmx:
      exposure:
        exclude: "*"
  endpoint:
    health:
      show-details: "always"
      probes:
        enabled: true

camunda.bpm:
  admin-user:
    id: demo
    password: demo
  metrics:
    db-reporter-activate: false
  database:
    schema-update: create-drop