version: '3.7'

networks:
  postrges:
    driver: bridge
    ipam:
      config:
        - subnet: 172.168.1.0/24

services:
  postgres_local:
    image: postgis/postgis:13-3.3-alpine
    container_name: postgres_local
    command: postgres -c 'max_connections=500'
    networks:
      postrges:
        ipv4_address: 172.168.1.2
    ports:
      - '5432:5432'
    environment:
      - DEBUG=false
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
    volumes:
      - /Users/denm/PostgresDB/LocalDB_13.0:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:6.21
    container_name: postgres_pgadmin
    networks:
      postrges:
        ipv4_address: 172.168.1.3
    depends_on:
      - postgres_local
    ports:
      - '80:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=user
    volumes:
      - /Users/denm/PostgresDB/PGAdmin_backup:/var/lib/pgadmin

  camunda-platform:
    image: camunda/camunda-bpm-platform:run-latest
    container_name: camunda-platform
    networks:
      postrges:
        ipv4_address: 172.168.1.4
    ports:
      - '8080:8080'